# ===============================
# PERFIL: DEV (desarrollo local)
# ===============================

# Base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestor_pedidos_dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP
spring.datasource.hikari.pool-name=GestorPedidosPool-DEV
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# JPA - mostrar SQL en dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging detallado en dev
logging.level.com.sergio.gestor_pedidos=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.liquibase=INFO

# CORS - permite el frontend local
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
